version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Use Node.js image
    working_directory: ~/repo

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests with verbose output
          command: |
            npx jest --verbose

workflows:
  version: 2
  test:
    jobs:
      - test
